apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadlyxi2773-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadlyxi2773-tenant-component
    app.kubernetes.io/part-of: loadlyxi2773-tenant-app
  name: loadlyxi2773-tenant-component
  namespace: loadlyxi2773-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadlyxi2773-tenant-component
status:
  loadBalancer: {}
